Added pr template
makeopensource/mOS pull request #17
Opened 2023-03-11 04:44 UTC by shawnz99

For issue #5 , Got most of this from bits and pieces of example templates across the web, I think it might be a bit much for now but I think its decent as a general template. Let me know what you guys like/don't like ect.

2023-03-11 22:56 UTC, Sploder12 requested changes
Overall very good, just some minor typos and the template file (at least from what I can tell from GitHub docs) should be named "pull_request_template.md"

2023-03-11 22:56 UTC, Sploder12 commented on README.md
> +
This will be changed soon (see #14 )

2023-03-11 22:56 UTC, Sploder12 commented on docs/PRTemplate.md
> +* OS
Test configuration would probably only amount to qemu version

2023-03-11 22:56 UTC, Sploder12 commented on docs/PRTemplate.md
> +- [ ] I have commented my code, paraticularly in hard-to-understand areas
typo: "paraticularly" should be "particularly"

2023-03-11 22:56 UTC, Sploder12 commented on docs/PRTemplate.md
> +Fixes # (issue)
Fixes implies existence of a problem. May be better to use Resolves or other github keyword to be more general to both bug-fixes and features.

2023-03-11 22:56 UTC, Sploder12 commented on docs/PRTemplate.md
> +Please describe tests that you ran to verify your changes. Provide instructions so that we can areproduce. Please also list any relevant details for your test configuration.
It might make sense to have a dedicated testing header. (Also we currently don't have a reliable way to test, but we are hoping to have unit tests in the future.)

typo: "areproduce" should be "reproduce"

2023-03-11 23:59 UTC, shawnz99 commented on README.md
> +
Shoot I didn't mean to get this added to the pr I just wanted to push it to github to see how the rendered markdown looked

2023-03-19 03:45 UTC, shawnz99 commented on docs/PRTemplate.md
> +Fixes # (issue)
Should  It just be issue #? that makes more sense to me than whatever I had there

2023-03-19 03:46 UTC, shawnz99 commented on docs/PRTemplate.md
> +* OS
My thought  behind this was more like OS that qemu is running on like windows, linux, macos ect.

2023-03-19 03:46 UTC, shawnz99 commented on docs/PRTemplate.md
> +Please describe tests that you ran to verify your changes. Provide instructions so that we can areproduce. Please also list any relevant details for your test configuration.
Like a testing section in the Pull request template?

2023-03-19 04:20 UTC, Sploder12 commented on docs/PRTemplate.md
> +* OS
Which would end up being something like "qemu x.y.z on JesseOS". Good to have but I don't think it needs a whole section

2023-03-19 04:28 UTC, Sploder12 commented on docs/PRTemplate.md
> +Fixes # (issue)
Definitely keep the summary. Having just the issue number would work.

2023-03-19 04:32 UTC, Sploder12 commented on docs/PRTemplate.md
> +Please describe tests that you ran to verify your changes. Provide instructions so that we can areproduce. Please also list any relevant details for your test configuration.
Probably a subheading of this section (### or something) then the testing paragraph and configuration would be in there. Although, if you don't think it's necessary we don't need it.

2023-03-20 16:11 UTC, Sploder12 approved these changes

2023-03-20 19:47 UTC, shawnz99 commented
> I'm not too familiar with templates but it the web has convinced me this file has to be named "pull_request_template.md", also that'd be more consistent with other MOS projects

Yeah I completely agree, the name I originally had was definitely _bad_ I just wasn't sure what else to name it.

2023-03-21 02:17 UTC, merged