PIT Implementation
makeopensource/mOS pull request #20
Opened 2023-03-21 04:21 UTC by shawnz99

# Description

 - Making use of the PIT chip
 - Global sense of "time" by keeping track of elapsed ticks
 - Ability to adjust frequency of the timer
 - Implementation of sleep
   -  Note that if we end up doing multitasking this will have to be changed. Can't do it now since afaik we don't have a concept of a "process"
 - Added a README.md detailing how a PIT works. 
   
This PR is for Issue #10 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

### Testing 
- From `main.c` (or really anywhere else but it makes the most sense here I think) you can call print out the tick count and see it increase as time progresses
- In `main.c` add
```c
println("Start Sleep", red);
sleep(100);
println("End Sleep", red);
```
and note that it takes a bit for end sleep to show up

**Test Configuration**:
* qemu 6.2.0 on Ubuntu 22.04

# Checklist:
	
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-03-21 16:35 UTC, Sploder12 requested changes
Looks good aside from some minor issues that need to be resolved. The README.md is extremely well made, I really like it.

2023-03-21 16:35 UTC, Sploder12 commented on src/lib/pit/pit.h
> + *  note that how long it sleeps for dur dpeends on what freq the timer is set at
Format of comments are different from existing comments. (then again, my many single comment chains are abnormal and purely a biproduct of `// ` being easier to type than ` * `) See soon to exist, style guide issue

typo: "dpeends" should be "depends"

2023-03-21 16:35 UTC, Sploder12 commented on src/lib/pit/pit.c
> +	}
`<=` should be `<`, this currently waits for `dur + 1` ticks. (can be verified with serial printing)

Micro-optimization: could be implemented as `while (timer_ticks < end)` where end is `timer_ticks + dur` at the start. This is a micro-optimization, I only mention it because this is a tight loop in a timing related function. However, it may make no difference at all, and as such, I will not require it.

2023-03-21 16:35 UTC, Sploder12 commented on src/lib/pit/pit.h
> +void timer_handler(isr_registers_t *regs);
I don't think this should be a public function. Calling it is not intended and it results in a race condition, since `inc` is not atomic. This would also allow us to move `#include "../../os/hard/idt.h"` to only the .c file

2023-03-21 16:35 UTC, Sploder12 commented on src/lib/pit/pit.h
> +#include "../../lib/video/VGA_text.h"
This include is unused and `"video/VGA_text.h"` is preferred

2023-03-21 16:35 UTC, Sploder12 commented on src/lib/pit/README.md
> +|         |                  |
this empty entry ends up looking weird

2023-03-21 16:35 UTC, Sploder12 commented on src/lib/pit/README.md
> +
inconsistent `\n` with rest of document, also .md likes to ignore things like this

2023-03-21 16:35 UTC, Sploder12 commented on src/lib/pit/pit.c
> +	init_timer(100);	// 100 hz is just a good general frequency according to the wiki
Since the PIT is already sending interrupts before `init_pit` (due to BIOS), masking/disabling the PIT or disabling interrupts should be done while performing setup to avoid possible race conditions.

2023-03-21 16:35 UTC, Sploder12 commented on src/lib/pit/pit.c
> +int timer_ticks = 0;
this value cannot be accessed outside of `pit.c`, there should probably be a function to get this value (returns a copy). Although, if you don't think it's necessary it is not needed.

2023-03-21 17:12 UTC, shawnz99 commented on src/lib/pit/pit.h
> + *  note that how long it sleeps for dur dpeends on what freq the timer is set at
I just did this out of habit but if we ever decide to use a documentation generator like doxygen itll automatically parse these comments and build documentation out of it

2023-03-21 22:23 UTC, Sploder12 commented on src/lib/pit/pit.c
> +	init_timer(100);	// 100 hz is just a good general frequency according to the wiki
(irqSetHandler is also a source of race conditions)

2023-04-04 19:59 UTC, Sploder12 commented on src/lib/pit/pit.h
> +#include "../../os/hard/port_io.h"
should be in the .c instead of .h

2023-04-04 20:00 UTC, Sploder12 commented on src/lib/pit/pit.c
> +	outb(CMD_REG_PORT, 0x36);	                /* Write 0b00110110 to the command register */
0x36 should be a macro

2023-04-04 22:21 UTC, shawnz99 commented on src/lib/pit/pit.c
> +	outb(CMD_REG_PORT, 0x36);	                /* Write 0b00110110 to the command register */
Idk I kinda disagree since 0x36 isn't a static value thats to be reused in several places its a specific combination of commands that set the channel, operating mode, access mode, and BCD/binary mode. I think the hex value itself is more explanatory than a macro would be

2023-04-04 23:36 UTC, Sploder12 commented on src/lib/pit/pit.c
> +	outb(CMD_REG_PORT, 0x36);	                /* Write 0b00110110 to the command register */
A macro may not be the best here. But I disagree with the hex being enough. Even with the binary representation comment, I wouldn't know the purpose of that specific number and i'd have to reference elsewhere to figure it out

2023-04-10 14:26 UTC, shawnz99 commented on src/lib/pit/pit.c
> +	outb(CMD_REG_PORT, 0x36);	                /* Write 0b00110110 to the command register */
one thought I had was to macro each part (channel, op mode, access mode, ect...) and then combine them there with bitwise operations but idk if that will make it better or more confusing

2023-04-10 14:48 UTC, Sploder12 commented on src/lib/pit/pit.c
> +	outb(CMD_REG_PORT, 0x36);	                /* Write 0b00110110 to the command register */
I think that'd work well

2023-04-18 20:42 UTC, Sploder12 approved these changes
Looks good!

2023-04-18 20:45 UTC, merged