Standard Library Functions
makeopensource/mOS pull request #22
Opened 2023-03-26 19:47 UTC by emilkovacev

# Description

Added a `stdlib` directory with the following C functions:
- sn_printf
- atoi
- strnlen_s
- strcpy_s
- strncmp
- memcpy

Added `tests/` directory with a variety of tests for each function, and a Makefile with `make`, `make clean`, and `make test` commands.

Added README.md for documenting how to use stdlib, write additional stdlib functions, and write additional tests

Issue #11 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

### Testing 
A testing directory was added in `/tests`. To reproduce, see the README, or simply use the Makefile command `$ make test`.

# Checklist:
	
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-03-26 21:04 UTC, Sploder12 requested changes
Very nice. Some compliance issues and sn_printf needs the integer conversion.

2023-03-26 21:16 UTC, emilkovacev commented on src/lib/stdlib/stdio.c
> +                    memcpy(buffer, s, strlen);
If it notices that the buffer is too large, should it just skip the formatting, or completely stop printing altogether?

2023-03-26 21:23 UTC, Sploder12 commented on src/lib/stdlib/stdio.c
> +                    memcpy(buffer, s, strlen);
probably stop printing

2023-03-26 21:35 UTC, emilkovacev commented on src/lib/stdlib/tests/test_stdio.c
> +    printf("%i tests failed\n", failed);
Once we add more tests it may not be! I followed a pattern for printing test output across all test files.

2023-03-26 21:47 UTC, Sploder12 commented on src/lib/stdlib/tests/test_stdio.c
> +    printf("%i tests failed\n", failed);
I was interpreting each case in the test function as a separate test, my bad

2023-03-26 22:01 UTC, Sploder12 commented on src/lib/stdlib/stdio.c
> +                    c = (char) va_arg(ap, unsigned int);
int was correct here

2023-03-27 03:24 UTC, Sploder12 commented on src/lib/stdlib/stdio.c
> +                char temp_buffer[bufSize];
this has a vulnerability when i is negative. bufSize will always be 1. The temp_buffer VLA is not needed, you could directly itoa buffer after checking the bounds

2023-03-27 03:30 UTC, emilkovacev commented on src/lib/stdlib/stdio.c
> +                char temp_buffer[bufSize];
Good catch on the vulnerability! If I swap if before the for loop it should prevent it from occurring I believe. 

As for the buffer, I create a temporary one so I can use the strlen function, which I need to check the bounds. I could, however, add a bound parameter to the `itoa` function, that way I don't have to make that check explicitly.

2023-03-27 03:31 UTC, Sploder12 commented on src/lib/stdlib/stdio.c
> +                char temp_buffer[bufSize];
since itoa is not a standard function, you may take whatever creative liberties you wish 😉

2023-03-29 00:12 UTC, emilkovacev commented on src/lib/stdlib/Makefile
> +CFLAGS := -g -Wall -Werror
This is proving difficult for the configuration I have set up, I was talking to nick about potentially creating a new branch where we can write tests to display instead of stdout.

2023-03-29 00:18 UTC, emilkovacev commented on src/lib/stdlib/Makefile
> +CFLAGS := -g -Wall -Werror
Although I see that you made an issue for testing, so we can wait for that before continuing forward?

2023-03-29 00:57 UTC, Sploder12 commented on src/lib/stdlib/Makefile
> +CFLAGS := -g -Wall -Werror
That would be fine.

2023-04-11 22:11 UTC, emilkovacev commented
I began migrating the tests from my implementation to @Sploder12's approach, so far it works well for stdlib! I'm not quite ready for another review, but soon...

2023-04-14 08:58 UTC, emilkovacev commented on src/lib/stdlib/Makefile
> +CFLAGS := -g -Wall -Werror
I managed to port the tests over to the new library! In order to make more efficient testing, I initialized `vsnprintf`, so that I could pass args to a helper function for testing. Essentially, my testing is all done with `vsnprintf`, because snprintf now just calls `vsnprintf` and does the appropriate, minimal initialization

2023-04-18 20:37 UTC, Sploder12 requested changes
Minor changes requested

2023-04-18 20:37 UTC, Sploder12 commented on src/lib/stdlib/stdio.c
> +            size_t strlen;
avoid naming variables the same as std functions.

2023-04-18 20:37 UTC, Sploder12 commented on src/lib/stdlib/string.c
> +    for (i = 0; i < destsz - 1 && src[i] != '\0'; i++) {
since this is _s, check src and dest for NULL!

2023-04-18 20:37 UTC, Sploder12 commented on src/lib/stdlib/string.c
> +        ((char *)dest)[i] = c;
cast to uint8_t* instead to avoid implicit conversion

2023-04-18 20:37 UTC, Sploder12 commented on src/lib/stdlib/string.c
> +        ((char *)dest)[i] = ((char *)src)[i];
bytes are uint8_t*, but char* does work here

2023-04-18 20:37 UTC, Sploder12 commented on src/lib/stdlib/stdlib.c
> +	char temp[digits+1];
evil VLA

2023-04-18 20:37 UTC, Sploder12 commented on tests/src/lib/stdlib/test_stdio.c
> +    serialWrite(COM1,  (uint8_t*)(done), sizeof(done));
writes '\0' to serial, might be an issue?

2023-04-18 20:37 UTC, Sploder12 commented on tests/src/lib/stdlib/test_string.c
> +    serialWrite(COM1, (uint8_t*)(done), 17);
use sizeof(done) - 1

2023-04-19 02:10 UTC, Sploder12 approved these changes
Everything looks good! **EXCEPT `test.py` NEEDS A SMALL CHANGE!!!! PLEASE DO NOT MERGE UNTIL THAT IS DONE**. I just don't want to make _another_ review when this is the only issue.

2023-04-19 02:10 UTC, Sploder12 commented on tests/test.py
> +>>>>>>> 2e5229979d8d9097f8b750b6fc7912a2656eb404
looks like someone forgot to fix the merge conflict 😔

2023-04-19 02:35 UTC, Sploder12 approved these changes
👍

2023-04-19 02:36 UTC, merged