Create Testing Environment
makeopensource/mOS pull request #24
Opened 2023-03-30 19:46 UTC by Sploder12

# Description

Creates a testing environment that is both (relatively) fast and easy to write new tests for.  
Also adds testing for the ring_buffer which also serves as an example on how to use the environment.  
  
Regarding the bugfix, qemu should no longer complain about raw. I did this since it was flooding the python output.  
Also, since this is such a large and important PR, I ask that at least two reviews from separate people are given prior to merging.

Issue #23 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Bug fix (non-breaking change which fixes an issue)

### Testing 
Ran python3 test.py on PowerShell after compiling through WSL, many, many times,

**Test Configuration**:
* qemu 7.2.0 on Windows 10 with WSL 5.10.16.3 running Ubuntu 20.04
* python 3.10.10

# Checklist:
	
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

note: I'd like to confirm this design before writing the associated README, README will be added later during this PR

2023-04-05 05:08 UTC, emilkovacev requested changes
Good stuff! It works on my VM, which is promising, and you seem to take good care in looking for edge cases. There are a few code style improvements I could suggest, but I'm not sure if that's worthwhile for the project.

I'd say the most pressing thing is adding a README. If we have instructions for running and especially adding our own tests in one place, it would be super easy to test more!

2023-04-05 05:08 UTC, emilkovacev commented on tests/test.py
> +                with open(instance.expected_path.path + ".got", "w") as gotF:
if you open and close the files like you do earlier in the code, this is a lot easier to read :)

2023-04-05 14:14 UTC, Sploder12 commented on tests/test.py
> +                with open(instance.expected_path.path + ".got", "w") as gotF:
I'm not entirely sure what you mean. Are you referencing the `+ ".got"` or `gotF` (or both)?

Also, all style improvement suggestions are welcome! The cleaner and more readable the better!

2023-04-05 14:19 UTC, emilkovacev commented on tests/test.py
> +                with open(instance.expected_path.path + ".got", "w") as gotF:
Sounds good!

I'm referencing the stacked `with` statements, because it seems to me you are reading and writing once!

2023-04-11 06:13 UTC, emilkovacev requested changes
The nitpickiest of nitpicks. Mostly style related. The last thing I'd like to do before we merge is test the stdlib functions with this library, and see if I can find any bugs that way!

2023-04-11 06:13 UTC, emilkovacev commented on tests/test.py
> +    print("See .got files for more details")
You could use formatted strings!

2023-04-11 06:26 UTC, Sploder12 commented on src/os/test.c
> +    serialWrite(COM1, (uint8_t*)("begin test"), 10);
Or we can do `sizeof(_) - 1` since it's a static string! Rare case of C being nice to us

2023-04-11 06:33 UTC, Sploder12 commented on src/os/main.c
> +        if (read > 256) read = 256;
I don't like this section, I'm just gonna rewrite it. (Featuring 100% less buffers, and 100% more indexing)

2023-04-11 21:06 UTC, emilkovacev requested changes
Some small things I found when moving the stdlib function tests over to the new framework!

\* Small note, during our meeting we found a discrepancy with how python is able to access the qemu executable across operating systems (specifically linux). @Sploder12's immediate, low-budget solution was to temporarily copy the executable for each asynchronous instance.

Once we have control over which tests to run at any given time, the above approach should be ok, since we would usually only want to run a couple of tests anyway.

2023-04-11 21:22 UTC, Sploder12 commented on tests/Makefile
> +all: $(MOS_ELF) $(BIN_NAMES)
rule $(MOS_ELF) should cover this

2023-04-11 22:04 UTC, emilkovacev commented on tests/Makefile
> +C_FILES := $(shell find ./src/ -name '*.c')
Once this is done, we are ready to merge!

2023-04-18 21:07 UTC, anxiety-fan approved these changes
The messages inside the example test are a little sparse, but I think that's a thing that's on the test-writer. Otherwise, everything seems to be in order. No unexpected behavior or particularly cursed looking code.

2023-04-18 21:11 UTC, anxiety-fan approved these changes
Take 2

2023-04-18 23:53 UTC, emilkovacev commented on tests/src/lib/container/ring_buffer.c
> +#define RB_SIZE 32
Would we want any checks with a ring buffer of size 0? I.e. are we ever expanding the size of the ring buffer? Probably not, and even still, we probably won't ever declare a ring buffer of size zero, but that would introduce some ok bounds checking scenarios.

2023-04-18 23:54 UTC, emilkovacev commented on tests/src/test_helper.h
We may want to include more helper functions here in the future, I certainly plan on adding a few. But this is certainly enough for 99% of testing, and I don't want to delay the PR over something like this

2023-04-18 23:56 UTC, emilkovacev approved these changes
I left some comments for future consideration, but given the importance of this testing environment, they are not worth blocking the PR. I was able to successfully use this to test and debug the stdlib in my PR, and it works very well! I am ready to say this can be merged :)

2023-04-19 00:11 UTC, Sploder12 commented on tests/src/lib/container/ring_buffer.c
> +#define RB_SIZE 32
Having a size of 0 would not be ISO standard C. The behavior would be compiler dependent.
The size of the ring buffer is not intended to change.

I would do `static_assert(size > 0);` if I could

2023-04-19 00:13 UTC, merged