Paging
makeopensource/mOS pull request #29
Opened 2023-04-21 22:22 UTC by Sploder12

# Description

Provides a way to interact with page tables and directories.
Also identity maps the first 12MiB.
Note: does not do allocation or anything that requires it. Intended for separate PR

Issue #28 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

### Testing 
Existing tests all pass.
In addition, tests were added to verify the identity paging is valid.
And for translation of virtual address to physical address.
And for swapping the active page directory.

**Test Configuration**:
* qemu 7.2.0 on Windows 10 with WSL 5.10.16.3 running Ubuntu 20.04
* python 3.10.10

# Checklist:
	
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-04-25 15:06 UTC, emilkovacev commented
I'm glad I waited a bit longer to make a review, the docs look excellent! I'll try to get a review out today, maybe before our meeting, but no promises

2023-06-11 16:01 UTC, bicknrown submitted a review, later dismissed
overall quite thorough, as far as i can tell, just some minor formatting/linting things and i'll be happy.
thank you for your effort!

2023-06-11 16:01 UTC, bicknrown commented on tests/src/os/paging.c
> +#define BOUND ((void *)(MiB1 * 4))
perhaps refactor this to the top? i'm fine with combined function definitions, defines, etc. in tests because of the one-off nature, and we can take that one by one. but this should *probably* go at the top with the others ;)

2023-06-11 16:03 UTC, bicknrown commented
the branch is also out of date with `main`, so i would see if that doesn't break anything either.

2023-06-11 19:23 UTC, Sploder12 commented on src/os/paging.c
> +    return ((uint32_t)(vaddr) >> PAGE_ENTRY_OFFSET) & 0b1111111111;
My reasoning for using binary here is that `0x3FF` (10bits set) I feel doesn't get the point across. `0xFFF` (12bits set) I feel is pretty clear. But Macros could be used instead

2023-06-11 19:25 UTC, Sploder12 commented on src/os/paging.c
> +bool pageEntryPresent(PageTableEntry entry) { return entry & ENTRY_PRESENT; }
will address with PS2 pr

2023-09-10 04:03 UTC, emilkovacev commented on src/os/paging.c
> +    return ((uint32_t)(vaddr) >> PAGE_ENTRY_OFFSET) & 0b1111111111;
`0x3ff` is easier to read, and deduce how many bits the mask is.

2023-09-13 02:40 UTC, emilkovacev requested changes
Superb documentation and commenting! I have but a few small suggestions – the tests run smoothly and qemu still runs well after these changes.

2023-09-13 02:40 UTC, emilkovacev commented on src/os/paging.c
> +    uint32_t baseAddr = idx * 0x400000;
✨ Magic numbers ✨ ;)

2023-09-13 02:40 UTC, emilkovacev commented on docs/os/paging.md
> +
A lot of your other documentation walks through the code to explain these concepts, it could be nice (but not necessarily essential) to include examples of where the page table is declared/add code snippets.

2023-09-13 02:42 UTC, Sploder12 commented on docs/os/paging.md
> +[Decomposition](vaddr_decomp.png)
Oops. good catch!

2023-09-13 02:55 UTC, Sploder12 commented on docs/os/paging.md
> +
The code related to the mappings is going to be pretty volatile and there aren't great examples for anything but Identity mapping. But, the Identity mapping is also subject to change. I think it might be best to update it once we get page allocation and/or elf loading

2023-09-13 03:20 UTC, emilkovacev commented on docs/os/paging.md
> +
I realize I highlighted just a few lines, but the comment addressed the entire document

2023-09-13 03:39 UTC, emilkovacev approved these changes
Everything appears to be in order!

2023-11-03 02:27 UTC, emilkovacev commented
I will use your paging library to complete an implementation of issue #30, if by that point I find additional features or things I may want, I will post them here.

2025-03-11 21:22 UTC, Real-Septicake commented
LGTM!

2025-03-11 21:22 UTC, merged