Qemu GDB
makeopensource/mOS pull request #42
Opened 2023-09-09 22:05 UTC by emilkovacev

# Description

GDB with qemu is a bit more involved than usual, so I added two commands to the Makefile, `qemu-gdb` and `qemu-gdb-boot`, for debugging in real and protected mode. I also added a doc explaining the details in `docs/gdb.md`.

There was no issue created for this task (I wrote it to work on #30)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

### Testing 
I ran `make test`, `make qemu`, and was able to run qemu through gdb with the two commands I created.

# Checklist:
	
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-09-09 22:44 UTC, Sploder12 requested changes
Awesome changes, this should make development much easier and faster.
Only some small things to address.

One issue I was getting was QEMU would sometimes take too long to start causing gdb to timeout the connection. This seems to be occurring because WSL is really slow. Is there an easy fix like waiting for QEMU to start? (not worth fixing if it isn't easy IMO)

2023-09-09 22:44 UTC, Sploder12 commented on docs/gdb.md
> +To run gdb with qemu, simple run `qemu-gdb`! An instance of qemu will run in the
Grammar:
"simple" should be "simply"

2023-09-09 22:44 UTC, Sploder12 commented on docs/gdb.md
> +few things happen when you run this. First, we load a few default settings and
Many newlines don't appear in the rendered markdown, is this intentional?

2023-09-09 22:44 UTC, Sploder12 commented on Makefile
> +export CFLAGS := -Wall -Werror -g -g3 -Os -Wl,--oformat=binary -no-pie -m32 -s -falign-functions=4 -ffreestanding -fno-asynchronous-unwind-tables
-g3 should make -g unnecessary

2023-09-09 22:44 UTC, Sploder12 commented on Makefile
> +BOOT_ELF := boot.elf
unused, can it be removed?

2023-09-09 22:46 UTC, emilkovacev commented on docs/gdb.md
> +few things happen when you run this. First, we load a few default settings and
Yes, I have my editor set up so it indents at 80 characters

2023-09-09 22:54 UTC, emilkovacev commented
> Awesome changes, this should make development much easier and faster. Only some small things to address.
> 
> One issue I was getting was QEMU would sometimes take too long to start causing gdb to timeout the connection. This seems to be occurring because WSL is really slow. Is there an easy fix like waiting for QEMU to start? (not worth fixing if it isn't easy IMO)

The easy fix would be doing it in two different windows – i.e. to run gdb you run `make qemu` in one window, and `make qemu-gdb` in another. It would make only *slightly* more inconvenient to do everything, but it's not a huge deal

2023-09-09 22:59 UTC, Sploder12 commented
> The easy fix would be doing it in two different windows – i.e. to run gdb you run `make qemu` in one window, and `make qemu-gdb` in another. We'd have to edit the commands to do that, otherwise we'd run the chance of having two instances open at the same time. It would make only _slightly_ more inconvenient to do everything, but it's not a huge deal

I like having a single command in a single window. I don't think it's worth it to change anything then

2023-09-09 23:39 UTC, emilkovacev commented
> > The easy fix would be doing it in two different windows – i.e. to run gdb you run `make qemu` in one window, and `make qemu-gdb` in another. We'd have to edit the commands to do that, otherwise we'd run the chance of having two instances open at the same time. It would make only _slightly_ more inconvenient to do everything, but it's not a huge deal
> 
> I like having a single command in a single window. I don't think it's worth it to change anything then

On second thought (and after a bit of research), we could also increase the timeout duration within gdb to something like 10 or 20 seconds through the `-ex` flag

2023-09-09 23:40 UTC, Sploder12 commented
> On second thought (and after a bit of research), we could also increase the timeout duration within gdb to something like 10 or 20 seconds through the `-ex` flag

That would probably work well

2023-09-10 00:49 UTC, emilkovacev commented
> > On second thought (and after a bit of research), we could also increase the timeout duration within gdb to something like 10 or 20 seconds through the `-ex` flag
> 
> That would probably work well

I pushed a commit with those changes, and added an `FAQ` section to the docs

2023-09-10 00:54 UTC, Sploder12 approved these changes

2023-09-10 00:54 UTC, merged