Type-agnostic sorting (insertion sort)
makeopensource/mOS pull request #52
Opened 2023-10-21 19:56 UTC by emilkovacev

# Description

I added insertion sort into stdlib (and made stdlib a common library for all c files to access). I also included thorough tests that demonstrate the type-agnostic approach (which C uses to implement qsort and heapsort). This function is useful in the issue #30 (Mallocation) because a small number of structures need to be sorted in-place.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)

### Testing 

I created tests for sorting arrays of integers, and custom type `Type` which includes an int, float, and char. These two types of arrays have their own `compar` function which compares two elements and returns an `int` of `-1, 0, 1` indicating the intended order. The test then sorts the arrays, and checks that the corresponding array follows the `compar` function ordering, and has the same elements as is expected.

**Test Configuration**:
* Hardware
* OS

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2023-10-21 20:31 UTC, Sploder12 requested changes
Some small thoughts, very nice!

2023-10-21 20:31 UTC, Sploder12 commented on src/lib/stdlib/stdlib.h
> +//   int (*compar)(const void *a, const void *b): comparison function between two void * values
Might be helpful to mention that it is a 3-way comparison

2023-10-21 20:31 UTC, Sploder12 commented on src/lib/stdlib/stdlib.c
> +            if (compar(a, b) == 1) {
might make sense to do `> 0` instead so C standard 3-way comparisons like `strcmp` can be used as-is (but I don't particularly like `strcmp` anyways)

2023-10-21 20:31 UTC, Sploder12 commented on src/lib/stdlib/stdlib.c
> +                memcpy(a, temp_b, width);
This could be done without a temporary buffer using the no temporary swap trick (interpreting the bytes as unsigned chars and doing _magic_). But it's not really necessary and the benefits aren't huge.

2023-10-21 20:31 UTC, Sploder12 commented on src/lib/stdlib/stdlib.c
> +    }
should we also check the width precondition here?

2023-10-21 20:31 UTC, Sploder12 commented on tests/src/lib/stdlib/test_sort.c
> +    };
Nice use of designated initializers! These tests are awesome!

2023-10-21 20:53 UTC, emilkovacev commented on src/lib/stdlib/stdlib.c
> +            if (compar(a, b) == 1) {
Coundn't strcmp be used either way? if it returns 0, they're equal, so it shouldn't really need to sort it in comparison to other values.

2023-10-21 20:55 UTC, emilkovacev commented on src/lib/stdlib/stdlib.c
> +                memcpy(a, temp_b, width);
That's actually awesome and I kind of want to do it! A memory swapping function could be useful to add to stdlib.

2023-10-21 21:13 UTC, Sploder12 commented on src/lib/stdlib/stdlib.c
> +            if (compar(a, b) == 1) {
`strcmp` may return something > 1 so the swap would never happen

2023-10-22 02:05 UTC, Sploder12 approved these changes
looks good!

2023-11-03 02:25 UTC, merged