Cursor movement and testing revamp
makeopensource/mOS pull request #56
Opened 2024-10-31 18:33 UTC by Real-Septicake

# Description

This pull request adds cursor movement via the arrow keys, character deletion via the `delete` and `backspace` keys, highlighting by moving the cursor while holding shift. Using the arrow keys while highlighting also changes the behavior slightly, such as the deletion keys also deleting the highlighted characters, or the . There are also some fixes to `test.py` and `vsnprintf` in `stdio.c` and a non-breaking revamp to the test assertion macro to allow for the printing of values for the purpose of debugging.

~~Issue #~~ (N/A, no issue was made for this)

## Type of change

- [x] New feature (non-breaking change which adds functionality)
^ Added cursor movement and highlighting, as well as more powerful testing utilities
- [x] Bug fix (non-breaking change which fixes an issue)
^ Fixed `vsnprintf`'s `%s` and `%i` format specifiers

### Testing 
Please describe tests that you ran to verify your changes. Provide instructions so that we can reproduce. Please also list any relevant details for your test configuration.

**Test Configuration**:
* Hardware
   * I'm not sure what to say here besides that I clicked the arrow keys, checked that highlighting worked properly, checked that highlighted behavior changes work properly
* OS
   * Wrote tests in `test_keyboard.c` with the help of @Alex105178, who made the initial framework for testing

# Checklist:
	
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2024-10-31 23:03 UTC, Sploder12 reviewed
More \n to improve readability!

2024-10-31 23:07 UTC, Real-Septicake commented on tests/src/test_helper.h
> +    char buff[1024];
256 would probably work, I just went with 1024 because I felt that it was a size we'd likely never push up against

2024-10-31 23:14 UTC, Real-Septicake commented on tests/src/test_helper.h
> +    char buff[1024];
Changed to 256 in the most recent commit

2024-11-01 18:45 UTC, Sploder12 commented on tests/test.py
> +                    print(self.bin_path.name + " was forcefully closed.")
I don't think `"\x01x"` never worked and it's basically the same as `.kill()`. It'd probably be best to replace `.communicate` with `.kill` to save a pretty significant amount of time on tests. Also we should really do a `.wait` after `.kill`.

2024-11-01 18:49 UTC, Sploder12 commented on tests/src/lib/stdlib/test_keyboard.c
> +#include "../../test_helper.h"
You need `../../`... for `test_helper.h`, but it isn't needed for the other includes. Maybe we should have `test_helper.h` in the gcc include path?

2024-11-01 19:05 UTC, Sploder12 commented on src/lib/device/ps2.c
> +    }
default case will clear the highlighted area. But, clearing the highlighted area doesn't seem like the correct behavior for keys that do not produce characters. For example, shift, ctrl, home, page up, page down, and end, will clear the highlighted area. Checking for `keyPressToASCII` returning `\0` would probably work?

2024-11-01 19:06 UTC, Real-Septicake commented on src/lib/device/ps2.c
> +    }
That won't be too hard to set up, I'll add that check

2024-11-01 19:08 UTC, Sploder12 commented on src/lib/video/VGA_text.c
> +#undef SIGNUM
`#undef` unnecessary and not grouped with other `#undef`

2024-11-01 19:11 UTC, Real-Septicake commented on src/lib/video/VGA_text.c
> +#undef SIGNUM
My guess is that I forgot that I wasn't in a header file, I'll remove those

2024-11-01 19:13 UTC, Real-Septicake commented on tests/test.py
> +                    print(self.bin_path.name + " was forcefully closed.")
That would explain why there was always a forced timeout. Would this still need he `.kill()` in the `except` block?

2024-11-01 19:17 UTC, Real-Septicake commented on tests/src/lib/stdlib/test_keyboard.c
> +#include "../../test_helper.h"
That would probably be a good idea. Would that just be adding a `-I` flag to the gcc command?

2024-11-01 19:20 UTC, Sploder12 commented on tests/test.py
> +                    print(self.bin_path.name + " was forcefully closed.")
Not needed, you can handle the `except` case as you see fit, something like failing the test or panicking would work. Something really bad must've happened for `SIGKILL` to not end QEMU. But now that I think about it more, `.terminate` in the `try` with `.kill` in the `except`  (with `.wait` after both) would probably be a better way to handle exiting QEMU

2024-11-01 19:21 UTC, Real-Septicake commented on tests/test.py
> +                    print(self.bin_path.name + " was forcefully closed.")
Alright, will do

2024-11-01 19:23 UTC, Sploder12 commented on tests/src/lib/stdlib/test_keyboard.c
> +#include "../../test_helper.h"
yep

2024-11-02 07:00 UTC, Sploder12 reviewed
Should tests be added for the `snprintf` bugs you caught?

2024-11-03 15:31 UTC, Sploder12 requested changes
Awesome PR! No major changes needed, mostly formatting and code reuse. My biggest suggestion is using newlines to separate code a bit more since everything is a bit squished without them.

2024-11-03 15:31 UTC, Sploder12 commented on tests/src/test_helper.h
> +    va_end(args);
lots of duplicated code from `_assert_fail_m`, code reuse is important since we have very limited size! (and binary size effects test time by a bit)

2024-11-03 15:31 UTC, Sploder12 commented on tests/src/test_helper.h
> +void _assert_fail_m(char *fmt, const char *assertion, unsigned line,
I would say "`fmt` should be `const char*`" but `snprintf` doesn't have `fmt` as `const` sooo.......

2024-11-03 15:31 UTC, Sploder12 commented on tests/src/lib/stdlib/test_keyboard.c
> +extern VGA_Char *cursor;
This implies it'd be nice to have a way to retrieve the cursor from `VGA_text.h`

2024-11-03 15:31 UTC, Sploder12 commented on tests/src/lib/stdlib/test_keyboard.c
> +    for (int i = 0; b[i].cmd != end; i++) {
since `b` is fixed size, you can use `sizeof(b)/sizeof(TestCMD)` (don't tell Ethan!) to get the size instead of remembering the terminate command.

2024-11-03 15:31 UTC, Sploder12 commented on tests/src/lib/stdlib/test_keyboard.c
> +        // written during boot
This is not a safe assumption and could make the tests fragile.

2024-11-03 15:31 UTC, Sploder12 commented on tests/src/lib/stdlib/test_keyboard.c
> +        chkPosCMD(END_LINE, END_COL),
This is a really neat approach, but it's very hard to understand what is happening. Comments, and more generally, more usage of \n would help a lot.

2024-11-04 20:09 UTC, Sploder12 commented on tests/Makefile
> +	$(VENV_PY) -m pip install termcolor
Prefer using requirements.txt

2024-11-04 20:11 UTC, Real-Septicake commented on tests/src/lib/stdlib/test_keyboard.c
> +    for (int i = 0; b[i].cmd != end; i++) {
That is true, I'd probably make use of both to allow for early termination of the tests
e.g. To isolate a problem from the following commands

2024-11-04 20:22 UTC, Real-Septicake commented on src/lib/device/ps2.c
> +int highlight_offset = 0;
That would probably work well, and would allow us to hold more information in one spot should the need arise

2024-11-04 20:28 UTC, Real-Septicake commented on tests/src/test_helper.h
> +    int len = snprintf(buff, sizeof(buff), errfmt, function, line, assertion);
That's fair, and I will make use of that, however I'm not sure that it would be able to make tests pass accidentally, unless we somehow manage to put in the mangled output in the `.expect` file
... I'm starting to think we should write tests for `test_helper.h` at this point

2024-11-04 20:40 UTC, Real-Septicake commented on tests/src/lib/stdlib/test_keyboard.c
> +        // written during boot
I'll add a `setPosCMD` command to be sure that the code is consistent

2024-11-04 21:00 UTC, Real-Septicake commented on src/lib/video/VGA_text.h
> +int cursorIsAtEnd(void);
Will do

2024-11-04 21:22 UTC, Sploder12 commented on tests/src/test_helper.h
> +    int len = snprintf(buff, sizeof(buff), errfmt, function, line, assertion);
If it outputs strings of 0 length consistently then failed assertions would generate no output. Since lots of tests rely on no output being good output it could break.
The other tests are the tests for `test_helper.h` 😉

2024-11-04 22:27 UTC, Real-Septicake commented on tests/Makefile
> +	$(VENV_PY) -m pip install termcolor
Will be done in the upcoming commit

2024-11-04 22:27 UTC, Real-Septicake commented on tests/src/lib/stdlib/test_keyboard.c
> +        chkPosCMD(END_LINE, END_COL),
I've separated them out and commented them in the upcoming commit

2024-11-04 22:29 UTC, Real-Septicake commented on tests/src/lib/stdlib/test_keyboard.c
> +        // written during boot
The position will be set manually in the upcoming commit

2024-11-04 22:32 UTC, Real-Septicake commented on src/lib/device/ps2.c
> +            break;
Most likely, and I've been trying to think about how I'd do so, but I can't think of a way to generalize it

2024-11-04 23:05 UTC, Sploder12 commented on src/lib/video/VGA_text.h
> +extern cursor_struct cursor;
I would not recommend it. I suggest making setter/getter or some other approach

2024-11-04 23:08 UTC, Sploder12 commented on src/lib/video/VGA_text.h
> +} cursor_struct;
The name `cursor_struct` could be a problem when we add mouse support. Perhaps a name that indicates its association to VGA, like `VGA_Cursor` would be better. WDYT?

2024-11-04 23:34 UTC, Real-Septicake commented on src/lib/video/VGA_text.h
> +} cursor_struct;
It has been changed to `VGA_Cursor` in the newest commit

2024-11-04 23:42 UTC, Real-Septicake commented on src/lib/video/VGA_text.h
> +extern cursor_struct cursor;
Trevor has spoken!
I'll add a getter, I don't think we'll need a setter unless we decide to support several cursors for whatever reason

2024-11-05 00:11 UTC, Real-Septicake commented on tests/src/test_helper.h
> +void _assert_fail_m(char *fmt, const char *assertion, unsigned line,
Would it be possible to make `fmt` `const` in snprintf? I've looked at it and it doesn't seem like it would cause any issues

2024-11-05 00:12 UTC, Real-Septicake commented on tests/src/lib/stdlib/test_keyboard.c
> +extern VGA_Char *cursor;
This has been set up in the most recent commits

2024-11-05 00:39 UTC, Sploder12 commented on tests/src/test_helper.h
> +void _assert_fail_m(char *fmt, const char *assertion, unsigned line,
go for it!

2024-11-05 00:56 UTC, Sploder12 commented on src/lib/device/ps2.c
> +            break;
My thought on how is the following procedure.
1. Apply the offset/change to position (you probably need to save the original state for later)
2. Check that the new position is valid, if not restore/truncate it
3. Calculate the area that is newly/no-longer highlighted, using something like a start and end pointer to VGA memory
4. Apply highlighting to that area

The only differing input is the offset/change to position. 

But there could be a better way to do it, so take it more as a starting point rather than a full solution.

2024-11-05 01:44 UTC, Real-Septicake commented on tests/src/test_helper.h
> +    va_end(args);
This has been fixed, both functions have been merged into one

2024-11-05 02:11 UTC, Real-Septicake commented on src/lib/device/ps2.c
> +            break;
This has been mostly fixed in the newest commit, it extracts a large portion of the logic, but likely isn't a perfect solution, with there likely being more to extract

2024-11-05 02:23 UTC, Sploder12 commented on src/lib/device/ps2.c
> +            break;
Good improvement but I think it can still be a bit better. One thing I'm looking at is the `if offset then highlight move else move highlight`, which I think can be reduced to just `move highlight`. But that's just a theory. A code theory!

2024-11-06 01:04 UTC, Real-Septicake commented on src/lib/device/ps2.c
> +            break;
Unfortunately, it cannot, as it leaves the previous character highlighted when moving back through the highlight, which is not the behavior we want

2024-11-15 01:43 UTC, Real-Septicake commented on src/lib/device/ps2.c
> +void specialHandler(struct PS2Buf_t out) {
The code has been moved to a `key_handlers` file, a naming scheme will have to be determined at some point for the functions that end up in there.

2024-12-05 00:32 UTC, Sploder12 requested changes
looks good! Color seems to not work on Windows for tests though

2024-12-05 00:32 UTC, Sploder12 commented on tests/test.py
> +from termcolor import cprint
the color seems to not work on Windows, output is `←[92mtest_string.bin PASSED←[0m`

2024-12-23 22:56 UTC, Sploder12 approved these changes
LGTM!

2025-01-23 02:43 UTC, merged